/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  /// <summary>
  /// 怪物武将信息
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class BattleMsgMonster : TBase
  {
    private int _index;
    private int _templateId;
    private List<sbyte> _shieldList;
    private Dictionary<int, int> _fighteProp;
    private Dictionary<sbyte, int> _dropMap;

    /// <summary>
    /// 位置Index
    /// </summary>
    public int Index
    {
      get
      {
        return _index;
      }
      set
      {
        __isset.index = true;
        this._index = value;
      }
    }

    /// <summary>
    /// 怪物模板ID
    /// </summary>
    public int TemplateId
    {
      get
      {
        return _templateId;
      }
      set
      {
        __isset.templateId = true;
        this._templateId = value;
      }
    }

    /// <summary>
    /// 护盾列表（测试用字段）
    /// </summary>
    public List<sbyte> ShieldList
    {
      get
      {
        return _shieldList;
      }
      set
      {
        __isset.shieldList = true;
        this._shieldList = value;
      }
    }

    /// <summary>
    /// 战斗属性map，hp,sp等（测试用字段）
    /// </summary>
    public Dictionary<int, int> FighteProp
    {
      get
      {
        return _fighteProp;
      }
      set
      {
        __isset.fighteProp = true;
        this._fighteProp = value;
      }
    }

    /// <summary>
    /// 战斗掉落
    /// </summary>
    public Dictionary<sbyte, int> DropMap
    {
      get
      {
        return _dropMap;
      }
      set
      {
        __isset.dropMap = true;
        this._dropMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool index;
      public bool templateId;
      public bool shieldList;
      public bool fighteProp;
      public bool dropMap;
    }

    public BattleMsgMonster() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Index = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              TemplateId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                ShieldList = new List<sbyte>();
                TList _list30 = iprot.ReadListBegin();
                for( int _i31 = 0; _i31 < _list30.Count; ++_i31)
                {
                  sbyte _elem32 = 0;
                  _elem32 = iprot.ReadByte();
                  ShieldList.Add(_elem32);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Map) {
              {
                FighteProp = new Dictionary<int, int>();
                TMap _map33 = iprot.ReadMapBegin();
                for( int _i34 = 0; _i34 < _map33.Count; ++_i34)
                {
                  int _key35;
                  int _val36;
                  _key35 = iprot.ReadI32();
                  _val36 = iprot.ReadI32();
                  FighteProp[_key35] = _val36;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.Map) {
              {
                DropMap = new Dictionary<sbyte, int>();
                TMap _map37 = iprot.ReadMapBegin();
                for( int _i38 = 0; _i38 < _map37.Count; ++_i38)
                {
                  sbyte _key39;
                  int _val40;
                  _key39 = iprot.ReadByte();
                  _val40 = iprot.ReadI32();
                  DropMap[_key39] = _val40;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("BattleMsgMonster");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.index) {
        field.Name = "index";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Index);
        oprot.WriteFieldEnd();
      }
      if (__isset.templateId) {
        field.Name = "templateId";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(TemplateId);
        oprot.WriteFieldEnd();
      }
      if (ShieldList != null && __isset.shieldList) {
        field.Name = "shieldList";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Byte, ShieldList.Count));
          foreach (sbyte _iter41 in ShieldList)
          {
            oprot.WriteByte(_iter41);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (FighteProp != null && __isset.fighteProp) {
        field.Name = "fighteProp";
        field.Type = TType.Map;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.I32, FighteProp.Count));
          foreach (int _iter42 in FighteProp.Keys)
          {
            oprot.WriteI32(_iter42);
            oprot.WriteI32(FighteProp[_iter42]);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (DropMap != null && __isset.dropMap) {
        field.Name = "dropMap";
        field.Type = TType.Map;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.Byte, TType.I32, DropMap.Count));
          foreach (sbyte _iter43 in DropMap.Keys)
          {
            oprot.WriteByte(_iter43);
            oprot.WriteI32(DropMap[_iter43]);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("BattleMsgMonster(");
      sb.Append("Index: ");
      sb.Append(Index);
      sb.Append(",TemplateId: ");
      sb.Append(TemplateId);
      sb.Append(",ShieldList: ");
      sb.Append(ShieldList);
      sb.Append(",FighteProp: ");
      sb.Append(FighteProp);
      sb.Append(",DropMap: ");
      sb.Append(DropMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
