/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  /// <summary>
  /// 怪物武将信息
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class BattleMsgMonster : TBase
  {
    private int _index;
    private int _templateId;
    private int _defaultCD;
    private List<sbyte> _shieldList;
    private Dictionary<int, int> _fighteProp;
    private Dictionary<sbyte, int> _dropMap;
    private int _aiID;
    private List<int> _skillList;

    /// <summary>
    /// 位置Index
    /// </summary>
    public int Index
    {
      get
      {
        return _index;
      }
      set
      {
        __isset.index = true;
        this._index = value;
      }
    }

    /// <summary>
    /// 怪物模板ID
    /// </summary>
    public int TemplateId
    {
      get
      {
        return _templateId;
      }
      set
      {
        __isset.templateId = true;
        this._templateId = value;
      }
    }

    /// <summary>
    /// 默认CD
    /// </summary>
    public int DefaultCD
    {
      get
      {
        return _defaultCD;
      }
      set
      {
        __isset.defaultCD = true;
        this._defaultCD = value;
      }
    }

    /// <summary>
    /// 护盾列表（测试用字段）
    /// </summary>
    public List<sbyte> ShieldList
    {
      get
      {
        return _shieldList;
      }
      set
      {
        __isset.shieldList = true;
        this._shieldList = value;
      }
    }

    /// <summary>
    /// 战斗属性map，hp,sp等（测试用字段）
    /// </summary>
    public Dictionary<int, int> FighteProp
    {
      get
      {
        return _fighteProp;
      }
      set
      {
        __isset.fighteProp = true;
        this._fighteProp = value;
      }
    }

    /// <summary>
    /// 战斗掉落
    /// </summary>
    public Dictionary<sbyte, int> DropMap
    {
      get
      {
        return _dropMap;
      }
      set
      {
        __isset.dropMap = true;
        this._dropMap = value;
      }
    }

    /// <summary>
    /// 怪物AI ID
    /// </summary>
    public int AiID
    {
      get
      {
        return _aiID;
      }
      set
      {
        __isset.aiID = true;
        this._aiID = value;
      }
    }

    /// <summary>
    /// 怪物技能列表
    /// </summary>
    public List<int> SkillList
    {
      get
      {
        return _skillList;
      }
      set
      {
        __isset.skillList = true;
        this._skillList = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool index;
      public bool templateId;
      public bool defaultCD;
      public bool shieldList;
      public bool fighteProp;
      public bool dropMap;
      public bool aiID;
      public bool skillList;
    }

    public BattleMsgMonster() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Index = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              TemplateId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              DefaultCD = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.List) {
              {
                ShieldList = new List<sbyte>();
                TList _list36 = iprot.ReadListBegin();
                for( int _i37 = 0; _i37 < _list36.Count; ++_i37)
                {
                  sbyte _elem38 = 0;
                  _elem38 = iprot.ReadByte();
                  ShieldList.Add(_elem38);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.Map) {
              {
                FighteProp = new Dictionary<int, int>();
                TMap _map39 = iprot.ReadMapBegin();
                for( int _i40 = 0; _i40 < _map39.Count; ++_i40)
                {
                  int _key41;
                  int _val42;
                  _key41 = iprot.ReadI32();
                  _val42 = iprot.ReadI32();
                  FighteProp[_key41] = _val42;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.Map) {
              {
                DropMap = new Dictionary<sbyte, int>();
                TMap _map43 = iprot.ReadMapBegin();
                for( int _i44 = 0; _i44 < _map43.Count; ++_i44)
                {
                  sbyte _key45;
                  int _val46;
                  _key45 = iprot.ReadByte();
                  _val46 = iprot.ReadI32();
                  DropMap[_key45] = _val46;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.I32) {
              AiID = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.List) {
              {
                SkillList = new List<int>();
                TList _list47 = iprot.ReadListBegin();
                for( int _i48 = 0; _i48 < _list47.Count; ++_i48)
                {
                  int _elem49 = 0;
                  _elem49 = iprot.ReadI32();
                  SkillList.Add(_elem49);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("BattleMsgMonster");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.index) {
        field.Name = "index";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Index);
        oprot.WriteFieldEnd();
      }
      if (__isset.templateId) {
        field.Name = "templateId";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(TemplateId);
        oprot.WriteFieldEnd();
      }
      if (__isset.defaultCD) {
        field.Name = "defaultCD";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(DefaultCD);
        oprot.WriteFieldEnd();
      }
      if (ShieldList != null && __isset.shieldList) {
        field.Name = "shieldList";
        field.Type = TType.List;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Byte, ShieldList.Count));
          foreach (sbyte _iter50 in ShieldList)
          {
            oprot.WriteByte(_iter50);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (FighteProp != null && __isset.fighteProp) {
        field.Name = "fighteProp";
        field.Type = TType.Map;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.I32, FighteProp.Count));
          foreach (int _iter51 in FighteProp.Keys)
          {
            oprot.WriteI32(_iter51);
            oprot.WriteI32(FighteProp[_iter51]);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (DropMap != null && __isset.dropMap) {
        field.Name = "dropMap";
        field.Type = TType.Map;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.Byte, TType.I32, DropMap.Count));
          foreach (sbyte _iter52 in DropMap.Keys)
          {
            oprot.WriteByte(_iter52);
            oprot.WriteI32(DropMap[_iter52]);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.aiID) {
        field.Name = "aiID";
        field.Type = TType.I32;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(AiID);
        oprot.WriteFieldEnd();
      }
      if (SkillList != null && __isset.skillList) {
        field.Name = "skillList";
        field.Type = TType.List;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I32, SkillList.Count));
          foreach (int _iter53 in SkillList)
          {
            oprot.WriteI32(_iter53);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("BattleMsgMonster(");
      sb.Append("Index: ");
      sb.Append(Index);
      sb.Append(",TemplateId: ");
      sb.Append(TemplateId);
      sb.Append(",DefaultCD: ");
      sb.Append(DefaultCD);
      sb.Append(",ShieldList: ");
      sb.Append(ShieldList);
      sb.Append(",FighteProp: ");
      sb.Append(FighteProp);
      sb.Append(",DropMap: ");
      sb.Append(DropMap);
      sb.Append(",AiID: ");
      sb.Append(AiID);
      sb.Append(",SkillList: ");
      sb.Append(SkillList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
