/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class BattleMonsterAIMsgAction : TBase
  {
    private int _id;
    private List<SkillRatePairMsgData> _defaultSkills;
    private List<MonsterSkillAIMsgData> _aiSkills;

    /// <summary>
    /// 怪物AI ID
    /// </summary>
    public int Id
    {
      get
      {
        return _id;
      }
      set
      {
        __isset.id = true;
        this._id = value;
      }
    }

    /// <summary>
    /// 默认技能列表信息
    /// </summary>
    public List<SkillRatePairMsgData> DefaultSkills
    {
      get
      {
        return _defaultSkills;
      }
      set
      {
        __isset.defaultSkills = true;
        this._defaultSkills = value;
      }
    }

    /// <summary>
    /// 怪物AI技能信息
    /// </summary>
    public List<MonsterSkillAIMsgData> AiSkills
    {
      get
      {
        return _aiSkills;
      }
      set
      {
        __isset.aiSkills = true;
        this._aiSkills = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool id;
      public bool defaultSkills;
      public bool aiSkills;
    }

    public BattleMonsterAIMsgAction() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Id = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                DefaultSkills = new List<SkillRatePairMsgData>();
                TList _list40 = iprot.ReadListBegin();
                for( int _i41 = 0; _i41 < _list40.Count; ++_i41)
                {
                  SkillRatePairMsgData _elem42 = new SkillRatePairMsgData();
                  _elem42 = new SkillRatePairMsgData();
                  _elem42.Read(iprot);
                  DefaultSkills.Add(_elem42);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                AiSkills = new List<MonsterSkillAIMsgData>();
                TList _list43 = iprot.ReadListBegin();
                for( int _i44 = 0; _i44 < _list43.Count; ++_i44)
                {
                  MonsterSkillAIMsgData _elem45 = new MonsterSkillAIMsgData();
                  _elem45 = new MonsterSkillAIMsgData();
                  _elem45.Read(iprot);
                  AiSkills.Add(_elem45);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("BattleMonsterAIMsgAction");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.id) {
        field.Name = "id";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Id);
        oprot.WriteFieldEnd();
      }
      if (DefaultSkills != null && __isset.defaultSkills) {
        field.Name = "defaultSkills";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, DefaultSkills.Count));
          foreach (SkillRatePairMsgData _iter46 in DefaultSkills)
          {
            _iter46.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (AiSkills != null && __isset.aiSkills) {
        field.Name = "aiSkills";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, AiSkills.Count));
          foreach (MonsterSkillAIMsgData _iter47 in AiSkills)
          {
            _iter47.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("BattleMonsterAIMsgAction(");
      sb.Append("Id: ");
      sb.Append(Id);
      sb.Append(",DefaultSkills: ");
      sb.Append(DefaultSkills);
      sb.Append(",AiSkills: ");
      sb.Append(AiSkills);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
