/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  /// <summary>
  /// 出售道具
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CSBuyBackItems : TBase
  {
    private List<short> _buybackItemIndexes;

    /// <summary>
    /// 回购道具背包内位置
    /// </summary>
    public List<short> BuybackItemIndexes
    {
      get
      {
        return _buybackItemIndexes;
      }
      set
      {
        __isset.buybackItemIndexes = true;
        this._buybackItemIndexes = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool buybackItemIndexes;
    }

    public CSBuyBackItems() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                BuybackItemIndexes = new List<short>();
                TList _list8 = iprot.ReadListBegin();
                for( int _i9 = 0; _i9 < _list8.Count; ++_i9)
                {
                  short _elem10 = 0;
                  _elem10 = iprot.ReadI16();
                  BuybackItemIndexes.Add(_elem10);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CSBuyBackItems");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (BuybackItemIndexes != null && __isset.buybackItemIndexes) {
        field.Name = "buybackItemIndexes";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I16, BuybackItemIndexes.Count));
          foreach (short _iter11 in BuybackItemIndexes)
          {
            oprot.WriteI16(_iter11);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CSBuyBackItems(");
      sb.Append("BuybackItemIndexes: ");
      sb.Append(BuybackItemIndexes);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
