/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  /// <summary>
  /// 武将绑定操作
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CSHeroBind : TBase
  {
    private List<long> _heroUuid;

    public List<long> HeroUuid
    {
      get
      {
        return _heroUuid;
      }
      set
      {
        __isset.heroUuid = true;
        this._heroUuid = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool heroUuid;
    }

    public CSHeroBind() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                HeroUuid = new List<long>();
                TList _list8 = iprot.ReadListBegin();
                for( int _i9 = 0; _i9 < _list8.Count; ++_i9)
                {
                  long _elem10 = 0;
                  _elem10 = iprot.ReadI64();
                  HeroUuid.Add(_elem10);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CSHeroBind");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (HeroUuid != null && __isset.heroUuid) {
        field.Name = "heroUuid";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I64, HeroUuid.Count));
          foreach (long _iter11 in HeroUuid)
          {
            oprot.WriteI64(_iter11);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CSHeroBind(");
      sb.Append("HeroUuid: ");
      sb.Append(HeroUuid);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
