/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  /// <summary>
  /// 道具绑定操作
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CSItemLockOper : TBase
  {
    private List<short> _operItemIndex;

    /// <summary>
    /// 道具背包内位置
    /// </summary>
    public List<short> OperItemIndex
    {
      get
      {
        return _operItemIndex;
      }
      set
      {
        __isset.operItemIndex = true;
        this._operItemIndex = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool operItemIndex;
    }

    public CSItemLockOper() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                OperItemIndex = new List<short>();
                TList _list12 = iprot.ReadListBegin();
                for( int _i13 = 0; _i13 < _list12.Count; ++_i13)
                {
                  short _elem14 = 0;
                  _elem14 = iprot.ReadI16();
                  OperItemIndex.Add(_elem14);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CSItemLockOper");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (OperItemIndex != null && __isset.operItemIndex) {
        field.Name = "operItemIndex";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I16, OperItemIndex.Count));
          foreach (short _iter15 in OperItemIndex)
          {
            oprot.WriteI16(_iter15);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CSItemLockOper(");
      sb.Append("OperItemIndex: ");
      sb.Append(OperItemIndex);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
