/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CSRaidBattleStartMsg : TBase
  {
    private int _raidId;
    private long _friendId;
    private sbyte _teamIndex;

    public int RaidId
    {
      get
      {
        return _raidId;
      }
      set
      {
        __isset.raidId = true;
        this._raidId = value;
      }
    }

    public long FriendId
    {
      get
      {
        return _friendId;
      }
      set
      {
        __isset.friendId = true;
        this._friendId = value;
      }
    }

    public sbyte TeamIndex
    {
      get
      {
        return _teamIndex;
      }
      set
      {
        __isset.teamIndex = true;
        this._teamIndex = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool raidId;
      public bool friendId;
      public bool teamIndex;
    }

    public CSRaidBattleStartMsg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              RaidId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              FriendId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Byte) {
              TeamIndex = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CSRaidBattleStartMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.raidId) {
        field.Name = "raidId";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(RaidId);
        oprot.WriteFieldEnd();
      }
      if (__isset.friendId) {
        field.Name = "friendId";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(FriendId);
        oprot.WriteFieldEnd();
      }
      if (__isset.teamIndex) {
        field.Name = "teamIndex";
        field.Type = TType.Byte;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(TeamIndex);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CSRaidBattleStartMsg(");
      sb.Append("RaidId: ");
      sb.Append(RaidId);
      sb.Append(",FriendId: ");
      sb.Append(FriendId);
      sb.Append(",TeamIndex: ");
      sb.Append(TeamIndex);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
