/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  /// <summary>
  /// 升级道具
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CSStrengthItem : TBase
  {
    private short _operItemIndex;
    private List<short> _choiceItemIndexes;

    /// <summary>
    /// 升级道具背包内位置
    /// </summary>
    public short OperItemIndex
    {
      get
      {
        return _operItemIndex;
      }
      set
      {
        __isset.operItemIndex = true;
        this._operItemIndex = value;
      }
    }

    /// <summary>
    /// 添加道具背包内位置
    /// </summary>
    public List<short> ChoiceItemIndexes
    {
      get
      {
        return _choiceItemIndexes;
      }
      set
      {
        __isset.choiceItemIndexes = true;
        this._choiceItemIndexes = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool operItemIndex;
      public bool choiceItemIndexes;
    }

    public CSStrengthItem() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I16) {
              OperItemIndex = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                ChoiceItemIndexes = new List<short>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  short _elem2 = 0;
                  _elem2 = iprot.ReadI16();
                  ChoiceItemIndexes.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CSStrengthItem");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.operItemIndex) {
        field.Name = "operItemIndex";
        field.Type = TType.I16;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(OperItemIndex);
        oprot.WriteFieldEnd();
      }
      if (ChoiceItemIndexes != null && __isset.choiceItemIndexes) {
        field.Name = "choiceItemIndexes";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I16, ChoiceItemIndexes.Count));
          foreach (short _iter3 in ChoiceItemIndexes)
          {
            oprot.WriteI16(_iter3);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CSStrengthItem(");
      sb.Append("OperItemIndex: ");
      sb.Append(OperItemIndex);
      sb.Append(",ChoiceItemIndexes: ");
      sb.Append(ChoiceItemIndexes);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
