/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace KXSGCodec
{
  /// <summary>
  /// 职业类型
  /// </summary>
  public enum JobType
  {
    /// <summary>
    /// 剑士
    /// </summary>
    SWORDSMAN = 1,
    /// <summary>
    /// 骑士
    /// </summary>
    KNIGHT = 2,
    /// <summary>
    /// 射手
    /// </summary>
    ARCHER = 3,
    /// <summary>
    /// 盾兵
    /// </summary>
    SHIELDER = 4,
    /// <summary>
    /// 谋士
    /// </summary>
    MASTER = 5,
  }
}
