/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MonsterSkillAIMsgData : TBase
  {
    private int _skillId;
    private int _rouletteRate;
    private int _weight;
    private int _conditionType;
    private string _conditionParam;

    public int SkillId
    {
      get
      {
        return _skillId;
      }
      set
      {
        __isset.skillId = true;
        this._skillId = value;
      }
    }

    public int RouletteRate
    {
      get
      {
        return _rouletteRate;
      }
      set
      {
        __isset.rouletteRate = true;
        this._rouletteRate = value;
      }
    }

    public int Weight
    {
      get
      {
        return _weight;
      }
      set
      {
        __isset.weight = true;
        this._weight = value;
      }
    }

    public int ConditionType
    {
      get
      {
        return _conditionType;
      }
      set
      {
        __isset.conditionType = true;
        this._conditionType = value;
      }
    }

    public string ConditionParam
    {
      get
      {
        return _conditionParam;
      }
      set
      {
        __isset.conditionParam = true;
        this._conditionParam = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool skillId;
      public bool rouletteRate;
      public bool weight;
      public bool conditionType;
      public bool conditionParam;
    }

    public MonsterSkillAIMsgData() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              SkillId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              RouletteRate = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              Weight = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              ConditionType = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              ConditionParam = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("MonsterSkillAIMsgData");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.skillId) {
        field.Name = "skillId";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(SkillId);
        oprot.WriteFieldEnd();
      }
      if (__isset.rouletteRate) {
        field.Name = "rouletteRate";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(RouletteRate);
        oprot.WriteFieldEnd();
      }
      if (__isset.weight) {
        field.Name = "weight";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Weight);
        oprot.WriteFieldEnd();
      }
      if (__isset.conditionType) {
        field.Name = "conditionType";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ConditionType);
        oprot.WriteFieldEnd();
      }
      if (ConditionParam != null && __isset.conditionParam) {
        field.Name = "conditionParam";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ConditionParam);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("MonsterSkillAIMsgData(");
      sb.Append("SkillId: ");
      sb.Append(SkillId);
      sb.Append(",RouletteRate: ");
      sb.Append(RouletteRate);
      sb.Append(",Weight: ");
      sb.Append(Weight);
      sb.Append(",ConditionType: ");
      sb.Append(ConditionType);
      sb.Append(",ConditionParam: ");
      sb.Append(ConditionParam);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
