/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class RecieveEnergyInfo : TBase
  {
    private long _friendUuid;
    private long _giveEnergyTime;
    private bool _recieveStatus;

    public long FriendUuid
    {
      get
      {
        return _friendUuid;
      }
      set
      {
        __isset.friendUuid = true;
        this._friendUuid = value;
      }
    }

    public long GiveEnergyTime
    {
      get
      {
        return _giveEnergyTime;
      }
      set
      {
        __isset.giveEnergyTime = true;
        this._giveEnergyTime = value;
      }
    }

    public bool RecieveStatus
    {
      get
      {
        return _recieveStatus;
      }
      set
      {
        __isset.recieveStatus = true;
        this._recieveStatus = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool friendUuid;
      public bool giveEnergyTime;
      public bool recieveStatus;
    }

    public RecieveEnergyInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              FriendUuid = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              GiveEnergyTime = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Bool) {
              RecieveStatus = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("RecieveEnergyInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.friendUuid) {
        field.Name = "friendUuid";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(FriendUuid);
        oprot.WriteFieldEnd();
      }
      if (__isset.giveEnergyTime) {
        field.Name = "giveEnergyTime";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(GiveEnergyTime);
        oprot.WriteFieldEnd();
      }
      if (__isset.recieveStatus) {
        field.Name = "recieveStatus";
        field.Type = TType.Bool;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(RecieveStatus);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("RecieveEnergyInfo(");
      sb.Append("FriendUuid: ");
      sb.Append(FriendUuid);
      sb.Append(",GiveEnergyTime: ");
      sb.Append(GiveEnergyTime);
      sb.Append(",RecieveStatus: ");
      sb.Append(RecieveStatus);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
