/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCAddItemsAndHeros : TBase
  {
    private List<KXSGCodec.HeroInfo> _heroInfos;
    private List<KXSGCodec.ItemInfo> _itemInfos;

    /// <summary>
    /// 武将信息
    /// </summary>
    public List<KXSGCodec.HeroInfo> HeroInfos
    {
      get
      {
        return _heroInfos;
      }
      set
      {
        __isset.heroInfos = true;
        this._heroInfos = value;
      }
    }

    /// <summary>
    /// 道具信息
    /// </summary>
    public List<KXSGCodec.ItemInfo> ItemInfos
    {
      get
      {
        return _itemInfos;
      }
      set
      {
        __isset.itemInfos = true;
        this._itemInfos = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool heroInfos;
      public bool itemInfos;
    }

    public SCAddItemsAndHeros() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                HeroInfos = new List<KXSGCodec.HeroInfo>();
                TList _list46 = iprot.ReadListBegin();
                for( int _i47 = 0; _i47 < _list46.Count; ++_i47)
                {
                  KXSGCodec.HeroInfo _elem48 = new KXSGCodec.HeroInfo();
                  _elem48 = new KXSGCodec.HeroInfo();
                  _elem48.Read(iprot);
                  HeroInfos.Add(_elem48);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                ItemInfos = new List<KXSGCodec.ItemInfo>();
                TList _list49 = iprot.ReadListBegin();
                for( int _i50 = 0; _i50 < _list49.Count; ++_i50)
                {
                  KXSGCodec.ItemInfo _elem51 = new KXSGCodec.ItemInfo();
                  _elem51 = new KXSGCodec.ItemInfo();
                  _elem51.Read(iprot);
                  ItemInfos.Add(_elem51);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCAddItemsAndHeros");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (HeroInfos != null && __isset.heroInfos) {
        field.Name = "heroInfos";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, HeroInfos.Count));
          foreach (KXSGCodec.HeroInfo _iter52 in HeroInfos)
          {
            _iter52.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (ItemInfos != null && __isset.itemInfos) {
        field.Name = "itemInfos";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, ItemInfos.Count));
          foreach (KXSGCodec.ItemInfo _iter53 in ItemInfos)
          {
            _iter53.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCAddItemsAndHeros(");
      sb.Append("HeroInfos: ");
      sb.Append(HeroInfos);
      sb.Append(",ItemInfos: ");
      sb.Append(ItemInfos);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
