/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  /// <summary>
  /// PVE战斗开始协议
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCBattlePveStartMsg : TBase
  {
    private long _uuid;
    private sbyte _battleType;
    private int _spMaxBuffId;
    private int _raidID;
    private List<KXSGCodec.BattleMsgHero> _fighterList;
    private List<KXSGCodec.BattleMsgMonster> _monsterList;

    /// <summary>
    /// 战斗UUID
    /// </summary>
    public long Uuid
    {
      get
      {
        return _uuid;
      }
      set
      {
        __isset.uuid = true;
        this._uuid = value;
      }
    }

    /// <summary>
    /// 战斗类型
    /// </summary>
    public sbyte BattleType
    {
      get
      {
        return _battleType;
      }
      set
      {
        __isset.battleType = true;
        this._battleType = value;
      }
    }

    /// <summary>
    /// SP蓝光BUFFId
    /// </summary>
    public int SpMaxBuffId
    {
      get
      {
        return _spMaxBuffId;
      }
      set
      {
        __isset.spMaxBuffId = true;
        this._spMaxBuffId = value;
      }
    }

    /// <summary>
    /// 副本ID
    /// </summary>
    public int RaidID
    {
      get
      {
        return _raidID;
      }
      set
      {
        __isset.raidID = true;
        this._raidID = value;
      }
    }

    /// <summary>
    /// 武将列表
    /// </summary>
    public List<KXSGCodec.BattleMsgHero> FighterList
    {
      get
      {
        return _fighterList;
      }
      set
      {
        __isset.fighterList = true;
        this._fighterList = value;
      }
    }

    /// <summary>
    /// 怪物列表
    /// </summary>
    public List<KXSGCodec.BattleMsgMonster> MonsterList
    {
      get
      {
        return _monsterList;
      }
      set
      {
        __isset.monsterList = true;
        this._monsterList = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool uuid;
      public bool battleType;
      public bool spMaxBuffId;
      public bool raidID;
      public bool fighterList;
      public bool monsterList;
    }

    public SCBattlePveStartMsg() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              Uuid = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Byte) {
              BattleType = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              SpMaxBuffId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              RaidID = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.List) {
              {
                FighterList = new List<KXSGCodec.BattleMsgHero>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  KXSGCodec.BattleMsgHero _elem2 = new KXSGCodec.BattleMsgHero();
                  _elem2 = new KXSGCodec.BattleMsgHero();
                  _elem2.Read(iprot);
                  FighterList.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.List) {
              {
                MonsterList = new List<KXSGCodec.BattleMsgMonster>();
                TList _list3 = iprot.ReadListBegin();
                for( int _i4 = 0; _i4 < _list3.Count; ++_i4)
                {
                  KXSGCodec.BattleMsgMonster _elem5 = new KXSGCodec.BattleMsgMonster();
                  _elem5 = new KXSGCodec.BattleMsgMonster();
                  _elem5.Read(iprot);
                  MonsterList.Add(_elem5);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCBattlePveStartMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.uuid) {
        field.Name = "uuid";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Uuid);
        oprot.WriteFieldEnd();
      }
      if (__isset.battleType) {
        field.Name = "battleType";
        field.Type = TType.Byte;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(BattleType);
        oprot.WriteFieldEnd();
      }
      if (__isset.spMaxBuffId) {
        field.Name = "spMaxBuffId";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(SpMaxBuffId);
        oprot.WriteFieldEnd();
      }
      if (__isset.raidID) {
        field.Name = "raidID";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(RaidID);
        oprot.WriteFieldEnd();
      }
      if (FighterList != null && __isset.fighterList) {
        field.Name = "fighterList";
        field.Type = TType.List;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, FighterList.Count));
          foreach (KXSGCodec.BattleMsgHero _iter6 in FighterList)
          {
            _iter6.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (MonsterList != null && __isset.monsterList) {
        field.Name = "monsterList";
        field.Type = TType.List;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, MonsterList.Count));
          foreach (KXSGCodec.BattleMsgMonster _iter7 in MonsterList)
          {
            _iter7.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCBattlePveStartMsg(");
      sb.Append("Uuid: ");
      sb.Append(Uuid);
      sb.Append(",BattleType: ");
      sb.Append(BattleType);
      sb.Append(",SpMaxBuffId: ");
      sb.Append(SpMaxBuffId);
      sb.Append(",RaidID: ");
      sb.Append(RaidID);
      sb.Append(",FighterList: ");
      sb.Append(FighterList);
      sb.Append(",MonsterList: ");
      sb.Append(MonsterList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
