/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  /// <summary>
  /// 背包达到上限
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCBagOverLimit : TBase
  {
    private sbyte _bagType;

    /// <summary>
    /// 1-武将背包 2-道具背包
    /// </summary>
    public sbyte BagType
    {
      get
      {
        return _bagType;
      }
      set
      {
        __isset.bagType = true;
        this._bagType = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool bagType;
    }

    public SCBagOverLimit() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Byte) {
              BagType = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCBagOverLimit");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.bagType) {
        field.Name = "bagType";
        field.Type = TType.Byte;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(BagType);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCBagOverLimit(");
      sb.Append("BagType: ");
      sb.Append(BagType);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
