/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  /// <summary>
  /// 领取体力
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCFriendRecieveEnergySucc : TBase
  {
    private long _friendUuid;

    public long FriendUuid
    {
      get
      {
        return _friendUuid;
      }
      set
      {
        __isset.friendUuid = true;
        this._friendUuid = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool friendUuid;
    }

    public SCFriendRecieveEnergySucc() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              FriendUuid = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCFriendRecieveEnergySucc");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.friendUuid) {
        field.Name = "friendUuid";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(FriendUuid);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCFriendRecieveEnergySucc(");
      sb.Append("FriendUuid: ");
      sb.Append(FriendUuid);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
