/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCHeroMaxExtend : TBase
  {
    private short _refreshHeroCountLimit;
    private int _refreshDiamond;

    public short RefreshHeroCountLimit
    {
      get
      {
        return _refreshHeroCountLimit;
      }
      set
      {
        __isset.refreshHeroCountLimit = true;
        this._refreshHeroCountLimit = value;
      }
    }

    public int RefreshDiamond
    {
      get
      {
        return _refreshDiamond;
      }
      set
      {
        __isset.refreshDiamond = true;
        this._refreshDiamond = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool refreshHeroCountLimit;
      public bool refreshDiamond;
    }

    public SCHeroMaxExtend() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I16) {
              RefreshHeroCountLimit = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              RefreshDiamond = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCHeroMaxExtend");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.refreshHeroCountLimit) {
        field.Name = "refreshHeroCountLimit";
        field.Type = TType.I16;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(RefreshHeroCountLimit);
        oprot.WriteFieldEnd();
      }
      if (__isset.refreshDiamond) {
        field.Name = "refreshDiamond";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(RefreshDiamond);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCHeroMaxExtend(");
      sb.Append("RefreshHeroCountLimit: ");
      sb.Append(RefreshHeroCountLimit);
      sb.Append(",RefreshDiamond: ");
      sb.Append(RefreshDiamond);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
