/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  /// <summary>
  /// 道具出售成功
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCItemSellSucc : TBase
  {
    private Dictionary<short, short> _itemIndexeChanges;

    /// <summary>
    /// 主背包删除道具到回购背包变更索引信息
    /// </summary>
    public Dictionary<short, short> ItemIndexeChanges
    {
      get
      {
        return _itemIndexeChanges;
      }
      set
      {
        __isset.itemIndexeChanges = true;
        this._itemIndexeChanges = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool itemIndexeChanges;
    }

    public SCItemSellSucc() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                ItemIndexeChanges = new Dictionary<short, short>();
                TMap _map8 = iprot.ReadMapBegin();
                for( int _i9 = 0; _i9 < _map8.Count; ++_i9)
                {
                  short _key10;
                  short _val11;
                  _key10 = iprot.ReadI16();
                  _val11 = iprot.ReadI16();
                  ItemIndexeChanges[_key10] = _val11;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCItemSellSucc");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ItemIndexeChanges != null && __isset.itemIndexeChanges) {
        field.Name = "itemIndexeChanges";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I16, TType.I16, ItemIndexeChanges.Count));
          foreach (short _iter12 in ItemIndexeChanges.Keys)
          {
            oprot.WriteI16(_iter12);
            oprot.WriteI16(ItemIndexeChanges[_iter12]);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCItemSellSucc(");
      sb.Append("ItemIndexeChanges: ");
      sb.Append(ItemIndexeChanges);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
