/**
 * Autogenerated by CodeGenerator
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
 
using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift.Protocol;

namespace KXSGCodec
{
    /// <summary>
    /// sc message type map util
    /// </summary>
    public class SCMessageHelper
    {
        public static TBase createMessage(short type)
        {
        	            if (type == MessageType.SC_BATTLE_PVE_START_MSG.GetHashCode())
            {
                return new SCBattlePveStartMsg();
            }
			            if (type == MessageType.SC_FRIEND_APPLY_LIST.GetHashCode())
            {
                return new SCFriendApplyList();
            }
			            if (type == MessageType.SC_FRIEND_APPLY_OPER_SUCC.GetHashCode())
            {
                return new SCFriendApplyOperSucc();
            }
			            if (type == MessageType.SC_FRIEND_APPLY_SUCC.GetHashCode())
            {
                return new SCFriendApplySucc();
            }
			            if (type == MessageType.SC_FRIEND_BIND_SUCC.GetHashCode())
            {
                return new SCFriendBindSucc();
            }
			            if (type == MessageType.SC_FRIEND_DELETE_SUCC.GetHashCode())
            {
                return new SCFriendDeleteSucc();
            }
			            if (type == MessageType.SC_FRIEND_EXTEND_SUCC.GetHashCode())
            {
                return new SCFriendExtendSucc();
            }
			            if (type == MessageType.SC_FRIEND_GIVE_ENERGY_SUCC.GetHashCode())
            {
                return new SCFriendGiveEnergySucc();
            }
			            if (type == MessageType.SC_FRIEND_LOADING_ALL.GetHashCode())
            {
                return new SCFriendLoadingAll();
            }
			            if (type == MessageType.SC_FRIEND_QUERY_BY_NAME.GetHashCode())
            {
                return new SCFriendQueryByName();
            }
			            if (type == MessageType.SC_FRIEND_RECIEVE_ENERGY_LIST.GetHashCode())
            {
                return new SCFriendRecieveEnergyList();
            }
			            if (type == MessageType.SC_FRIEND_RECIEVE_ENERGY_SUCC.GetHashCode())
            {
                return new SCFriendRecieveEnergySucc();
            }
			            if (type == MessageType.SC_HERO_BIND_SUCC.GetHashCode())
            {
                return new SCHeroBindSucc();
            }
			            if (type == MessageType.SC_HERO_CHANGE_EQUIP.GetHashCode())
            {
                return new SCHeroChangeEquip();
            }
			            if (type == MessageType.SC_HERO_CHANGE_TEAM_SUCC.GetHashCode())
            {
                return new SCHeroChangeTeamSucc();
            }
			            if (type == MessageType.SC_HERO_CREATE_ONE.GetHashCode())
            {
                return new SCHeroCreateOne();
            }
			            if (type == MessageType.SC_HERO_LIST.GetHashCode())
            {
                return new SCHeroList();
            }
			            if (type == MessageType.SC_HERO_LVL_UP.GetHashCode())
            {
                return new SCHeroLvlUp();
            }
			            if (type == MessageType.SC_HERO_MAX_EXTEND.GetHashCode())
            {
                return new SCHeroMaxExtend();
            }
			            if (type == MessageType.SC_HERO_MODIFY_TEAM.GetHashCode())
            {
                return new SCHeroModifyTeam();
            }
			            if (type == MessageType.SC_HERO_SELL.GetHashCode())
            {
                return new SCHeroSell();
            }
			            if (type == MessageType.SC_ADD_ITEM.GetHashCode())
            {
                return new SCAddItem();
            }
			            if (type == MessageType.SC_ALL_ITEM_INFOS.GetHashCode())
            {
                return new SCAllItemInfos();
            }
			            if (type == MessageType.SC_BUY_BACK_ITEM_SUCC.GetHashCode())
            {
                return new SCBuyBackItemSucc();
            }
			            if (type == MessageType.SC_DELETE_ITEMS.GetHashCode())
            {
                return new SCDeleteItems();
            }
			            if (type == MessageType.SC_EVOLUTE_ITEM_SUCC.GetHashCode())
            {
                return new SCEvoluteItemSucc();
            }
			            if (type == MessageType.SC_EXTEND_ITEM_BAG_SUCC.GetHashCode())
            {
                return new SCExtendItemBagSucc();
            }
			            if (type == MessageType.SC_ITEM_DETAIL.GetHashCode())
            {
                return new SCItemDetail();
            }
			            if (type == MessageType.SC_ITEM_LOCK_OPER_SUCC.GetHashCode())
            {
                return new SCItemLockOperSucc();
            }
			            if (type == MessageType.SC_ITEM_SELL_SUCC.GetHashCode())
            {
                return new SCItemSellSucc();
            }
			            if (type == MessageType.SC_STRENGTH_ITEM_SUCC.GetHashCode())
            {
                return new SCStrengthItemSucc();
            }
			            if (type == MessageType.SC_CREATE_PLAYER_MSG.GetHashCode())
            {
                return new SCCreatePlayerMsg();
            }
			            if (type == MessageType.SC_PLAYER_INFO_MSG.GetHashCode())
            {
                return new SCPlayerInfoMsg();
            }
			            if (type == MessageType.SC_RANDOM_CHAR_NAME_MSG.GetHashCode())
            {
                return new SCRandomCharNameMsg();
            }
			            if (type == MessageType.SC_RECHARGE_ID_MSG.GetHashCode())
            {
                return new SCRechargeIdMsg();
            }
			            if (type == MessageType.SC_SERVER_LIST_MSG.GetHashCode())
            {
                return new SCServerListMsg();
            }
			            if (type == MessageType.SC_LOTTERY.GetHashCode())
            {
                return new SCLottery();
            }
			            if (type == MessageType.SC_LOTTERY_CANNOT_FREE.GetHashCode())
            {
                return new SCLotteryCannotFree();
            }
			            if (type == MessageType.SC_LOTTERY_COMPOSE_LIST.GetHashCode())
            {
                return new SCLotteryComposeList();
            }
			            if (type == MessageType.SC_LOTTERY_COMPOSE_SUCC.GetHashCode())
            {
                return new SCLotteryComposeSucc();
            }
			            if (type == MessageType.SC_LOTTERY_LIST.GetHashCode())
            {
                return new SCLotteryList();
            }
			            if (type == MessageType.SC_LOTTERY_REFRESH_TIMES.GetHashCode())
            {
                return new SCLotteryRefreshTimes();
            }
			            if (type == MessageType.SC_PROPERTY_CHANGED_NUMBER.GetHashCode())
            {
                return new SCPropertyChangedNumber();
            }
			            if (type == MessageType.SC_PROPERTY_CHANGED_STRING.GetHashCode())
            {
                return new SCPropertyChangedString();
            }
			            if (type == MessageType.SC_ADD_ITEMS_AND_HEROS.GetHashCode())
            {
                return new SCAddItemsAndHeros();
            }
			            if (type == MessageType.SC_ENERGY_NOT_ENOUGH.GetHashCode())
            {
                return new SCEnergyNotEnough();
            }
			            if (type == MessageType.SC_RAID_ADDTION.GetHashCode())
            {
                return new SCRaidAddtion();
            }
			            if (type == MessageType.SC_RAID_CLEAR_DAILY_TIMES.GetHashCode())
            {
                return new SCRaidClearDailyTimes();
            }
			            if (type == MessageType.SC_RAID_ENTER_FAIL.GetHashCode())
            {
                return new SCRaidEnterFail();
            }
			            if (type == MessageType.SC_RAID_FINISH_ADD_FRIEND.GetHashCode())
            {
                return new SCRaidFinishAddFriend();
            }
			            if (type == MessageType.SC_RAID_LOADING_ALL.GetHashCode())
            {
                return new SCRaidLoadingAll();
            }
			            if (type == MessageType.SC_RAID_NEW_STAGE.GetHashCode())
            {
                return new SCRaidNewStage();
            }
			            if (type == MessageType.SC_RAID_QUERY_FRIEND.GetHashCode())
            {
                return new SCRaidQueryFriend();
            }
			            if (type == MessageType.SC_RAID_RECEIVE_AWARDS.GetHashCode())
            {
                return new SCRaidReceiveAwards();
            }
			            if (type == MessageType.SC_RAID_REWARD.GetHashCode())
            {
                return new SCRaidReward();
            }
			            if (type == MessageType.SC_ERROR_INFO_MSG.GetHashCode())
            {
                return new SCErrorInfoMsg();
            }
			            if (type == MessageType.SC_SERVER_CONFIG_MSG.GetHashCode())
            {
                return new SCServerConfigMsg();
            }
			            if (type == MessageType.SC_SYSTEM_INFO_MSG.GetHashCode())
            {
                return new SCSystemInfoMsg();
            }
			 			Logger.LogError("Unknown sc msg type: " + type.ToString());
	        return null;

        }
    }
}