/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCRaidReceiveAwards : TBase
  {
    private int _raidId;
    private List<KXSGCodec.RewardItem> _rewardItem;

    public int RaidId
    {
      get
      {
        return _raidId;
      }
      set
      {
        __isset.raidId = true;
        this._raidId = value;
      }
    }

    public List<KXSGCodec.RewardItem> RewardItem
    {
      get
      {
        return _rewardItem;
      }
      set
      {
        __isset.rewardItem = true;
        this._rewardItem = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool raidId;
      public bool rewardItem;
    }

    public SCRaidReceiveAwards() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              RaidId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                RewardItem = new List<KXSGCodec.RewardItem>();
                TList _list42 = iprot.ReadListBegin();
                for( int _i43 = 0; _i43 < _list42.Count; ++_i43)
                {
                  KXSGCodec.RewardItem _elem44 = new KXSGCodec.RewardItem();
                  _elem44 = new KXSGCodec.RewardItem();
                  _elem44.Read(iprot);
                  RewardItem.Add(_elem44);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCRaidReceiveAwards");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.raidId) {
        field.Name = "raidId";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(RaidId);
        oprot.WriteFieldEnd();
      }
      if (RewardItem != null && __isset.rewardItem) {
        field.Name = "rewardItem";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, RewardItem.Count));
          foreach (KXSGCodec.RewardItem _iter45 in RewardItem)
          {
            _iter45.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCRaidReceiveAwards(");
      sb.Append("RaidId: ");
      sb.Append(RaidId);
      sb.Append(",RewardItem: ");
      sb.Append(RewardItem);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
