/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCRaidNewStage : TBase
  {
    private int _raidTemplateId;
    private int _stageTemplateId;

    public int RaidTemplateId
    {
      get
      {
        return _raidTemplateId;
      }
      set
      {
        __isset.raidTemplateId = true;
        this._raidTemplateId = value;
      }
    }

    public int StageTemplateId
    {
      get
      {
        return _stageTemplateId;
      }
      set
      {
        __isset.stageTemplateId = true;
        this._stageTemplateId = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool raidTemplateId;
      public bool stageTemplateId;
    }

    public SCRaidNewStage() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              RaidTemplateId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              StageTemplateId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCRaidNewStage");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.raidTemplateId) {
        field.Name = "raidTemplateId";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(RaidTemplateId);
        oprot.WriteFieldEnd();
      }
      if (__isset.stageTemplateId) {
        field.Name = "stageTemplateId";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(StageTemplateId);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCRaidNewStage(");
      sb.Append("RaidTemplateId: ");
      sb.Append(RaidTemplateId);
      sb.Append(",StageTemplateId: ");
      sb.Append(StageTemplateId);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
