/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CSHeroModifyTeam : TBase
  {
    private sbyte _teamIndex;
    private List<long> _newTeamList;

    public sbyte TeamIndex
    {
      get
      {
        return _teamIndex;
      }
      set
      {
        __isset.teamIndex = true;
        this._teamIndex = value;
      }
    }

    public List<long> NewTeamList
    {
      get
      {
        return _newTeamList;
      }
      set
      {
        __isset.newTeamList = true;
        this._newTeamList = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool teamIndex;
      public bool newTeamList;
    }

    public CSHeroModifyTeam() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Byte) {
              TeamIndex = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                NewTeamList = new List<long>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  long _elem2 = 0;
                  _elem2 = iprot.ReadI64();
                  NewTeamList.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CSHeroModifyTeam");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.teamIndex) {
        field.Name = "teamIndex";
        field.Type = TType.Byte;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(TeamIndex);
        oprot.WriteFieldEnd();
      }
      if (NewTeamList != null && __isset.newTeamList) {
        field.Name = "newTeamList";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I64, NewTeamList.Count));
          foreach (long _iter3 in NewTeamList)
          {
            oprot.WriteI64(_iter3);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CSHeroModifyTeam(");
      sb.Append("TeamIndex: ");
      sb.Append(TeamIndex);
      sb.Append(",NewTeamList: ");
      sb.Append(NewTeamList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
