/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace KXSGCodec
{
  public enum ErrorType
  {
    DECODE_EXCEPTION = 0,
    ILLEGAL_REQUEST = 1,
  }
}
