/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace KXSGCodec
{
  public enum MessageType
  {
    CS_BEGIN = 100,
    CS_USER_PASSWD = 101,
    CS_QUICK_LOGIN = 102,
    CS_END = 103,
    SC_BEGIN = 2000,
    SC_USER_INFO = 2001,
    SC_SYSTEM_INFO = 2002,
    SC_ERROR_INFO = 2003,
    SC_END = 2004,
  }
}
