/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace KXSGCodec
{

  /// <summary>
  /// 数值类型属性变化消息
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SCPropertyChangedNumber : TBase
  {
    private short _roleType;
    private long _uuid;
    private Dictionary<int, int> _propertyChanged;

    /// <summary>
    /// 角色类型
    /// </summary>
    public short RoleType
    {
      get
      {
        return _roleType;
      }
      set
      {
        __isset.roleType = true;
        this._roleType = value;
      }
    }

    public long Uuid
    {
      get
      {
        return _uuid;
      }
      set
      {
        __isset.uuid = true;
        this._uuid = value;
      }
    }

    /// <summary>
    /// 改变的属性
    /// </summary>
    public Dictionary<int, int> PropertyChanged
    {
      get
      {
        return _propertyChanged;
      }
      set
      {
        __isset.propertyChanged = true;
        this._propertyChanged = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool roleType;
      public bool uuid;
      public bool propertyChanged;
    }

    public SCPropertyChangedNumber() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I16) {
              RoleType = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              Uuid = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Map) {
              {
                PropertyChanged = new Dictionary<int, int>();
                TMap _map0 = iprot.ReadMapBegin();
                for( int _i1 = 0; _i1 < _map0.Count; ++_i1)
                {
                  int _key2;
                  int _val3;
                  _key2 = iprot.ReadI32();
                  _val3 = iprot.ReadI32();
                  PropertyChanged[_key2] = _val3;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SCPropertyChangedNumber");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.roleType) {
        field.Name = "roleType";
        field.Type = TType.I16;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(RoleType);
        oprot.WriteFieldEnd();
      }
      if (__isset.uuid) {
        field.Name = "uuid";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Uuid);
        oprot.WriteFieldEnd();
      }
      if (PropertyChanged != null && __isset.propertyChanged) {
        field.Name = "propertyChanged";
        field.Type = TType.Map;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.I32, PropertyChanged.Count));
          foreach (int _iter4 in PropertyChanged.Keys)
          {
            oprot.WriteI32(_iter4);
            oprot.WriteI32(PropertyChanged[_iter4]);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SCPropertyChangedNumber(");
      sb.Append("RoleType: ");
      sb.Append(RoleType);
      sb.Append(",Uuid: ");
      sb.Append(Uuid);
      sb.Append(",PropertyChanged: ");
      sb.Append(PropertyChanged);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
