/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Template.Auto.Raid
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Raid : TBase
  {
    private Dictionary<int, RaidTemplate> _raidTmpls;
    private Dictionary<int, RaidStageTemplate> _raidStageTmpls;
    private Dictionary<int, RaidMonsterGroupTemplate> _raidMonsterGroupTmpls;

    /// <summary>
    /// 副本模板信息
    /// </summary>
    public Dictionary<int, RaidTemplate> RaidTmpls
    {
      get
      {
        return _raidTmpls;
      }
      set
      {
        __isset.raidTmpls = true;
        this._raidTmpls = value;
      }
    }

    /// <summary>
    /// 关卡模板信息
    /// </summary>
    public Dictionary<int, RaidStageTemplate> RaidStageTmpls
    {
      get
      {
        return _raidStageTmpls;
      }
      set
      {
        __isset.raidStageTmpls = true;
        this._raidStageTmpls = value;
      }
    }

    /// <summary>
    /// 怪物组信息
    /// </summary>
    public Dictionary<int, RaidMonsterGroupTemplate> RaidMonsterGroupTmpls
    {
      get
      {
        return _raidMonsterGroupTmpls;
      }
      set
      {
        __isset.raidMonsterGroupTmpls = true;
        this._raidMonsterGroupTmpls = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool raidTmpls;
      public bool raidStageTmpls;
      public bool raidMonsterGroupTmpls;
    }

    public Raid() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                RaidTmpls = new Dictionary<int, RaidTemplate>();
                TMap _map4 = iprot.ReadMapBegin();
                for( int _i5 = 0; _i5 < _map4.Count; ++_i5)
                {
                  int _key6;
                  RaidTemplate _val7;
                  _key6 = iprot.ReadI32();
                  _val7 = new RaidTemplate();
                  _val7.Read(iprot);
                  RaidTmpls[_key6] = _val7;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Map) {
              {
                RaidStageTmpls = new Dictionary<int, RaidStageTemplate>();
                TMap _map8 = iprot.ReadMapBegin();
                for( int _i9 = 0; _i9 < _map8.Count; ++_i9)
                {
                  int _key10;
                  RaidStageTemplate _val11;
                  _key10 = iprot.ReadI32();
                  _val11 = new RaidStageTemplate();
                  _val11.Read(iprot);
                  RaidStageTmpls[_key10] = _val11;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Map) {
              {
                RaidMonsterGroupTmpls = new Dictionary<int, RaidMonsterGroupTemplate>();
                TMap _map12 = iprot.ReadMapBegin();
                for( int _i13 = 0; _i13 < _map12.Count; ++_i13)
                {
                  int _key14;
                  RaidMonsterGroupTemplate _val15;
                  _key14 = iprot.ReadI32();
                  _val15 = new RaidMonsterGroupTemplate();
                  _val15.Read(iprot);
                  RaidMonsterGroupTmpls[_key14] = _val15;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Raid");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (RaidTmpls != null && __isset.raidTmpls) {
        field.Name = "raidTmpls";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, RaidTmpls.Count));
          foreach (int _iter16 in RaidTmpls.Keys)
          {
            oprot.WriteI32(_iter16);
            RaidTmpls[_iter16].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (RaidStageTmpls != null && __isset.raidStageTmpls) {
        field.Name = "raidStageTmpls";
        field.Type = TType.Map;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, RaidStageTmpls.Count));
          foreach (int _iter17 in RaidStageTmpls.Keys)
          {
            oprot.WriteI32(_iter17);
            RaidStageTmpls[_iter17].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (RaidMonsterGroupTmpls != null && __isset.raidMonsterGroupTmpls) {
        field.Name = "raidMonsterGroupTmpls";
        field.Type = TType.Map;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, RaidMonsterGroupTmpls.Count));
          foreach (int _iter18 in RaidMonsterGroupTmpls.Keys)
          {
            oprot.WriteI32(_iter18);
            RaidMonsterGroupTmpls[_iter18].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Raid(");
      sb.Append("RaidTmpls: ");
      sb.Append(RaidTmpls);
      sb.Append(",RaidStageTmpls: ");
      sb.Append(RaidStageTmpls);
      sb.Append(",RaidMonsterGroupTmpls: ");
      sb.Append(RaidMonsterGroupTmpls);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
