/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Template.Auto.Raid
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Raid : TBase
  {
    private Dictionary<int, RaidTemplate> _raidTmpls;
    private Dictionary<int, RaidStageTemplate> _raidStageTmpls;

    /// <summary>
    /// 副本模板信息
    /// </summary>
    public Dictionary<int, RaidTemplate> RaidTmpls
    {
      get
      {
        return _raidTmpls;
      }
      set
      {
        __isset.raidTmpls = true;
        this._raidTmpls = value;
      }
    }

    /// <summary>
    /// 关卡模板信息
    /// </summary>
    public Dictionary<int, RaidStageTemplate> RaidStageTmpls
    {
      get
      {
        return _raidStageTmpls;
      }
      set
      {
        __isset.raidStageTmpls = true;
        this._raidStageTmpls = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool raidTmpls;
      public bool raidStageTmpls;
    }

    public Raid() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                RaidTmpls = new Dictionary<int, RaidTemplate>();
                TMap _map0 = iprot.ReadMapBegin();
                for( int _i1 = 0; _i1 < _map0.Count; ++_i1)
                {
                  int _key2;
                  RaidTemplate _val3;
                  _key2 = iprot.ReadI32();
                  _val3 = new RaidTemplate();
                  _val3.Read(iprot);
                  RaidTmpls[_key2] = _val3;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Map) {
              {
                RaidStageTmpls = new Dictionary<int, RaidStageTemplate>();
                TMap _map4 = iprot.ReadMapBegin();
                for( int _i5 = 0; _i5 < _map4.Count; ++_i5)
                {
                  int _key6;
                  RaidStageTemplate _val7;
                  _key6 = iprot.ReadI32();
                  _val7 = new RaidStageTemplate();
                  _val7.Read(iprot);
                  RaidStageTmpls[_key6] = _val7;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Raid");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (RaidTmpls != null && __isset.raidTmpls) {
        field.Name = "raidTmpls";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, RaidTmpls.Count));
          foreach (int _iter8 in RaidTmpls.Keys)
          {
            oprot.WriteI32(_iter8);
            RaidTmpls[_iter8].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (RaidStageTmpls != null && __isset.raidStageTmpls) {
        field.Name = "raidStageTmpls";
        field.Type = TType.Map;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, RaidStageTmpls.Count));
          foreach (int _iter9 in RaidStageTmpls.Keys)
          {
            oprot.WriteI32(_iter9);
            RaidStageTmpls[_iter9].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Raid(");
      sb.Append("RaidTmpls: ");
      sb.Append(RaidTmpls);
      sb.Append(",RaidStageTmpls: ");
      sb.Append(RaidStageTmpls);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
