// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public sealed class MtaAppMonitor
{
	// 成功
	public static int SUCCESS_RESULT_TYPE = 0;

	// 失败，表示接口本身不可用 ，可触发接口健康度告警

	public static int FAILURE_RESULT_TYPE = 1;

	// 逻辑失败，接口本身可用，但返回了逻辑错误 ， 不会触发接口健康度告警

	public static int LOGIC_FAILURE_RESULT_TYPE = 2;

	public MtaAppMonitor (string interfaceName)
	{
			this.interfaceName = interfaceName;
	}

	// 接口名称，默认为""，开发者在调用时，必须设置一个interfaceName
	private string interfaceName = "";
	public string InterfaceName 
	{
		get{ return interfaceName;}
	}

	// 请求包大小，单位：byte，默认为0
	private long requestSize = 0;
	public long RequestSize
	{
		get {return requestSize;}
		set {requestSize = value;}
	}

	// 响应包大小，单位：byte，默认为0
	private long responseSize = 0;
	public long ResponseSize
	{
		get {return responseSize;}
		set {responseSize = value;}
	}

	// 返回值类型，默认为SUCCESS_RESULT_TYPE
	private int resultType = SUCCESS_RESULT_TYPE;
	public int ResultType
	{
		get { return resultType; }
		set { resultType = value; }
	}

	// 调用耗时，单位：毫秒（ms），默认为0
	private long millisecondsConsume = 0;
	public long MillisecondsConsume {
		get {
			return this.millisecondsConsume;
		}
		set {
			millisecondsConsume = value;
		}
	}
	// 具体返回码，默认为0

	private int returnCode = 0;
	public int ReturnCode {
		get {
			return this.returnCode;
		}
		set {
			returnCode = value;
		}
	}


	// 采样率，默认为1，表示100%
	private int sampling = 1;
	public int Sampling {
		get {
			return this.sampling;
		}
		set {
			sampling = value;
		}
	}
}

