// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public sealed class MtaGameUser
{
	public MtaGameUser (string account, string worldName, string level)
	{
		this.account = account;
		this.worldName = worldName;
		this.level = level;
	}
	public MtaGameUser(string account)
	{
		this.account = account;
	}
	private string worldName = "";
	public string WorldName {
		get {
			return this.worldName;
		}
		set {
			worldName = value;
		}
	}
	private string account = "";
	public string Account {
		get {
			return this.account;
		}
		set {
			account = value;
		}
	}
	private string level = "";
	public string Level {
		get {
			return this.level;
		}
		set {
			level = value;
		}
	}


}


