/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Template
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Bag : TBase
  {
    private Dictionary<int, BagBaseTemplate> _bagBaseTmpl;
    private Dictionary<int, HeroBagExtendTemplate> _heroExtTmpl;
    private Dictionary<int, ItemBagExtendTemplate> _itemExtTmpl;

    public Dictionary<int, BagBaseTemplate> BagBaseTmpl
    {
      get
      {
        return _bagBaseTmpl;
      }
      set
      {
        __isset.bagBaseTmpl = true;
        this._bagBaseTmpl = value;
      }
    }

    public Dictionary<int, HeroBagExtendTemplate> HeroExtTmpl
    {
      get
      {
        return _heroExtTmpl;
      }
      set
      {
        __isset.heroExtTmpl = true;
        this._heroExtTmpl = value;
      }
    }

    public Dictionary<int, ItemBagExtendTemplate> ItemExtTmpl
    {
      get
      {
        return _itemExtTmpl;
      }
      set
      {
        __isset.itemExtTmpl = true;
        this._itemExtTmpl = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool bagBaseTmpl;
      public bool heroExtTmpl;
      public bool itemExtTmpl;
    }

    public Bag() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                BagBaseTmpl = new Dictionary<int, BagBaseTemplate>();
                TMap _map0 = iprot.ReadMapBegin();
                for( int _i1 = 0; _i1 < _map0.Count; ++_i1)
                {
                  int _key2;
                  BagBaseTemplate _val3;
                  _key2 = iprot.ReadI32();
                  _val3 = new BagBaseTemplate();
                  _val3.Read(iprot);
                  BagBaseTmpl[_key2] = _val3;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Map) {
              {
                HeroExtTmpl = new Dictionary<int, HeroBagExtendTemplate>();
                TMap _map4 = iprot.ReadMapBegin();
                for( int _i5 = 0; _i5 < _map4.Count; ++_i5)
                {
                  int _key6;
                  HeroBagExtendTemplate _val7;
                  _key6 = iprot.ReadI32();
                  _val7 = new HeroBagExtendTemplate();
                  _val7.Read(iprot);
                  HeroExtTmpl[_key6] = _val7;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Map) {
              {
                ItemExtTmpl = new Dictionary<int, ItemBagExtendTemplate>();
                TMap _map8 = iprot.ReadMapBegin();
                for( int _i9 = 0; _i9 < _map8.Count; ++_i9)
                {
                  int _key10;
                  ItemBagExtendTemplate _val11;
                  _key10 = iprot.ReadI32();
                  _val11 = new ItemBagExtendTemplate();
                  _val11.Read(iprot);
                  ItemExtTmpl[_key10] = _val11;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Bag");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (BagBaseTmpl != null && __isset.bagBaseTmpl) {
        field.Name = "bagBaseTmpl";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, BagBaseTmpl.Count));
          foreach (int _iter12 in BagBaseTmpl.Keys)
          {
            oprot.WriteI32(_iter12);
            BagBaseTmpl[_iter12].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (HeroExtTmpl != null && __isset.heroExtTmpl) {
        field.Name = "heroExtTmpl";
        field.Type = TType.Map;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, HeroExtTmpl.Count));
          foreach (int _iter13 in HeroExtTmpl.Keys)
          {
            oprot.WriteI32(_iter13);
            HeroExtTmpl[_iter13].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (ItemExtTmpl != null && __isset.itemExtTmpl) {
        field.Name = "itemExtTmpl";
        field.Type = TType.Map;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, ItemExtTmpl.Count));
          foreach (int _iter14 in ItemExtTmpl.Keys)
          {
            oprot.WriteI32(_iter14);
            ItemExtTmpl[_iter14].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Bag(");
      sb.Append("BagBaseTmpl: ");
      sb.Append(BagBaseTmpl);
      sb.Append(",HeroExtTmpl: ");
      sb.Append(HeroExtTmpl);
      sb.Append(",ItemExtTmpl: ");
      sb.Append(ItemExtTmpl);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
