/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Template
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Raid : TBase
  {
    private Dictionary<int, RaidTemplate> _raidTmpl;
    private Dictionary<int, RaidStageTemplate> _raidStageTmpl;

    /// <summary>
    /// 副本模板信息
    /// </summary>
    public Dictionary<int, RaidTemplate> RaidTmpl
    {
      get
      {
        return _raidTmpl;
      }
      set
      {
        __isset.raidTmpl = true;
        this._raidTmpl = value;
      }
    }

    /// <summary>
    /// 关卡模板信息
    /// </summary>
    public Dictionary<int, RaidStageTemplate> RaidStageTmpl
    {
      get
      {
        return _raidStageTmpl;
      }
      set
      {
        __isset.raidStageTmpl = true;
        this._raidStageTmpl = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool raidTmpl;
      public bool raidStageTmpl;
    }

    public Raid() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                RaidTmpl = new Dictionary<int, RaidTemplate>();
                TMap _map0 = iprot.ReadMapBegin();
                for( int _i1 = 0; _i1 < _map0.Count; ++_i1)
                {
                  int _key2;
                  RaidTemplate _val3;
                  _key2 = iprot.ReadI32();
                  _val3 = new RaidTemplate();
                  _val3.Read(iprot);
                  RaidTmpl[_key2] = _val3;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Map) {
              {
                RaidStageTmpl = new Dictionary<int, RaidStageTemplate>();
                TMap _map4 = iprot.ReadMapBegin();
                for( int _i5 = 0; _i5 < _map4.Count; ++_i5)
                {
                  int _key6;
                  RaidStageTemplate _val7;
                  _key6 = iprot.ReadI32();
                  _val7 = new RaidStageTemplate();
                  _val7.Read(iprot);
                  RaidStageTmpl[_key6] = _val7;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Raid");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (RaidTmpl != null && __isset.raidTmpl) {
        field.Name = "raidTmpl";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, RaidTmpl.Count));
          foreach (int _iter8 in RaidTmpl.Keys)
          {
            oprot.WriteI32(_iter8);
            RaidTmpl[_iter8].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (RaidStageTmpl != null && __isset.raidStageTmpl) {
        field.Name = "raidStageTmpl";
        field.Type = TType.Map;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, RaidStageTmpl.Count));
          foreach (int _iter9 in RaidStageTmpl.Keys)
          {
            oprot.WriteI32(_iter9);
            RaidStageTmpl[_iter9].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Raid(");
      sb.Append("RaidTmpl: ");
      sb.Append(RaidTmpl);
      sb.Append(",RaidStageTmpl: ");
      sb.Append(RaidStageTmpl);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
