/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Template.Auto.Level
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class LevelUp : TBase
  {
    private Dictionary<int, LevelUpBaseTemplate> _levelUpBaseTmpls;
    private Dictionary<int, LevelUpTemplate> _levelUpTmpls;

    public Dictionary<int, LevelUpBaseTemplate> LevelUpBaseTmpls
    {
      get
      {
        return _levelUpBaseTmpls;
      }
      set
      {
        __isset.levelUpBaseTmpls = true;
        this._levelUpBaseTmpls = value;
      }
    }

    public Dictionary<int, LevelUpTemplate> LevelUpTmpls
    {
      get
      {
        return _levelUpTmpls;
      }
      set
      {
        __isset.levelUpTmpls = true;
        this._levelUpTmpls = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool levelUpBaseTmpls;
      public bool levelUpTmpls;
    }

    public LevelUp() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                LevelUpBaseTmpls = new Dictionary<int, LevelUpBaseTemplate>();
                TMap _map0 = iprot.ReadMapBegin();
                for( int _i1 = 0; _i1 < _map0.Count; ++_i1)
                {
                  int _key2;
                  LevelUpBaseTemplate _val3;
                  _key2 = iprot.ReadI32();
                  _val3 = new LevelUpBaseTemplate();
                  _val3.Read(iprot);
                  LevelUpBaseTmpls[_key2] = _val3;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Map) {
              {
                LevelUpTmpls = new Dictionary<int, LevelUpTemplate>();
                TMap _map4 = iprot.ReadMapBegin();
                for( int _i5 = 0; _i5 < _map4.Count; ++_i5)
                {
                  int _key6;
                  LevelUpTemplate _val7;
                  _key6 = iprot.ReadI32();
                  _val7 = new LevelUpTemplate();
                  _val7.Read(iprot);
                  LevelUpTmpls[_key6] = _val7;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("LevelUp");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (LevelUpBaseTmpls != null && __isset.levelUpBaseTmpls) {
        field.Name = "levelUpBaseTmpls";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, LevelUpBaseTmpls.Count));
          foreach (int _iter8 in LevelUpBaseTmpls.Keys)
          {
            oprot.WriteI32(_iter8);
            LevelUpBaseTmpls[_iter8].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (LevelUpTmpls != null && __isset.levelUpTmpls) {
        field.Name = "levelUpTmpls";
        field.Type = TType.Map;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, LevelUpTmpls.Count));
          foreach (int _iter9 in LevelUpTmpls.Keys)
          {
            oprot.WriteI32(_iter9);
            LevelUpTmpls[_iter9].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("LevelUp(");
      sb.Append("LevelUpBaseTmpls: ");
      sb.Append(LevelUpBaseTmpls);
      sb.Append(",LevelUpTmpls: ");
      sb.Append(LevelUpTmpls);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
