/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Template.Auto.Sign
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Sign : TBase
  {
    private Dictionary<int, SignTemplate> _signTmpls;

    public Dictionary<int, SignTemplate> SignTmpls
    {
      get
      {
        return _signTmpls;
      }
      set
      {
        __isset.signTmpls = true;
        this._signTmpls = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool signTmpls;
    }

    public Sign() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                SignTmpls = new Dictionary<int, SignTemplate>();
                TMap _map4 = iprot.ReadMapBegin();
                for( int _i5 = 0; _i5 < _map4.Count; ++_i5)
                {
                  int _key6;
                  SignTemplate _val7;
                  _key6 = iprot.ReadI32();
                  _val7 = new SignTemplate();
                  _val7.Read(iprot);
                  SignTmpls[_key6] = _val7;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Sign");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (SignTmpls != null && __isset.signTmpls) {
        field.Name = "signTmpls";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, SignTmpls.Count));
          foreach (int _iter8 in SignTmpls.Keys)
          {
            oprot.WriteI32(_iter8);
            SignTmpls[_iter8].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Sign(");
      sb.Append("SignTmpls: ");
      sb.Append(SignTmpls);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
